FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY worker-service/pom.xml .
COPY worker-service/src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/worker-service-*.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
