FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY ingest-service/pom.xml .
COPY ingest-service/src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/ingest-service-*.jar /app/app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
