FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY producer/pom.xml .
COPY producer/src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/producer-*.jar /app/app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
